# Generated by rspec-sinatra. (2015-09-20 16:59:34 +0200)

ENV['RACK_ENV'] = 'test'

require File.join(File.dirname(__FILE__), '..', 'lib/rps_demo.rb')

require 'capybara'
require 'capybara/rspec'
require 'rspec'
require 'rack/test'

def app
  RPSDemo
end

Capybara.app = RPSDemo

RSpec.configure do |config|
  config.include Capybara::DSL
  config.include Rack::Test::Methods
  config.expect_with :rspec do |expectations|
    expectations.include_chain_clauses_in_custom_matcher_descriptions = true
  end

  config.mock_with :rspec do |mocks|
    mocks.verify_partial_doubles = true
  end
  
end
